from __future__ import annotations

from collections.abc import Iterable
import json
import os
from pathlib import Path
import re
import tempfile
from typing import Any

import yaml

from runbook_tools.catalog.model import CatalogEntry, CatalogError


SCHEMA_VERSION = 1
CATALOG_PATH = "CATALOG.json"
ROUTER_PATH = "TOPIC-ROUTER.md"
README_PATH = "README.md"
GENERATED_BANNER = "<!-- Generated by runbook-catalog. DO NOT EDIT. -->"
README_BEGIN = "<!-- runbook-catalog:begin -->"
README_END = "<!-- runbook-catalog:end -->"
FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*(?:\n|$)", re.DOTALL)


def source_paths(repo_root: Path) -> list[Path]:
    """Return the complete catalog source set, explicitly and deterministically.

    Catalog membership scans root ``*.md`` plus ``runbooks/**/*.md``. It excludes
    ``archive/**``, README.md, TOPIC-ROUTER.md, specs/**, audits/**, tests/**,
    templates/**, and generated artifacts. This is only the Chunk 1 catalog
    membership set; it does not select documents for the Chunk 2 stale-term scan.
    """
    root = repo_root.resolve()
    candidates = list(root.glob("*.md"))
    runbooks_root = root / "runbooks"
    if runbooks_root.is_dir():
        candidates.extend(runbooks_root.rglob("*.md"))

    selected: list[Path] = []
    for path in candidates:
        relative = path.relative_to(root)
        if path.name in {README_PATH, ROUTER_PATH}:
            continue
        if any(part in {"archive", "specs", "audits", "tests", "templates"} for part in relative.parts):
            continue
        selected.append(path)
    return sorted(set(selected), key=lambda path: path.relative_to(root).as_posix())


def build_catalog(repo_root: Path) -> tuple[dict[str, Any], int]:
    entries: list[CatalogEntry] = []
    grandfathered_count = 0
    root = repo_root.resolve()

    for path in source_paths(root):
        relative = path.relative_to(root).as_posix()
        frontmatter = _frontmatter(path)
        if frontmatter is None:
            grandfathered_count += 1
            continue
        if frontmatter.get("status") == "ACTIVE" and "runbook_id" not in frontmatter:
            raise CatalogError(f"{relative}: ACTIVE document is missing required runbook_id")
        if "runbook_id" not in frontmatter:
            grandfathered_count += 1
            continue
        if "status" not in frontmatter:
            raise CatalogError(f"{relative}: catalog opt-in is missing required status")
        if frontmatter.get("status") != "ACTIVE":
            continue
        entries.append(CatalogEntry.from_frontmatter(frontmatter, relative))

    entries.sort(key=lambda entry: entry.runbook_id)
    _validate_conflicts(entries)
    catalog = {
        "entries": [entry.as_dict() for entry in entries],
        "indexes": _build_indexes(entries),
        "schema_version": SCHEMA_VERSION,
    }
    return catalog, grandfathered_count


def render_outputs(repo_root: Path) -> dict[str, bytes]:
    catalog, grandfathered_count = build_catalog(repo_root)
    catalog_bytes = (json.dumps(catalog, indent=2, sort_keys=True) + "\n").encode()
    router_bytes = _render_router(catalog).encode()
    readme_path = repo_root / README_PATH
    if not readme_path.is_file():
        raise CatalogError(f"{README_PATH}: file is required for generated inventory")
    readme_bytes = _render_readme(readme_path.read_text(), catalog, grandfathered_count).encode()
    return {
        CATALOG_PATH: catalog_bytes,
        ROUTER_PATH: router_bytes,
        README_PATH: readme_bytes,
    }


def generate_catalog(repo_root: Path) -> dict[str, bytes]:
    outputs = render_outputs(repo_root)
    for relative, content in outputs.items():
        _atomic_write(repo_root / relative, content)
    return outputs


def check_catalog(repo_root: Path) -> list[str]:
    outputs = render_outputs(repo_root)
    drifted: list[str] = []
    for relative, expected in outputs.items():
        path = repo_root / relative
        if not path.is_file() or path.read_bytes() != expected:
            drifted.append(relative)
    return drifted


def _frontmatter(path: Path) -> dict[str, Any] | None:
    text = path.read_text()
    match = FRONTMATTER_RE.match(text)
    if match is None:
        return None
    raw_frontmatter = match.group(1)
    # Grandfathered Markdown may begin with a thematic break that resembles an
    # invalid YAML block. An explicit runbook_id or ACTIVE status opts a document
    # into YAML catalog parsing and its strict failure behavior.
    has_catalog_id = re.search(r"(?m)^runbook_id\s*:", raw_frontmatter) is not None
    has_active_status = re.search(r"(?m)^status\s*:\s*ACTIVE\s*$", raw_frontmatter) is not None
    if not has_catalog_id and not has_active_status:
        return None
    try:
        value = yaml.safe_load(raw_frontmatter)
    except yaml.YAMLError as exc:
        raise CatalogError(f"{path}: invalid YAML frontmatter: {exc}") from exc
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise CatalogError(f"{path}: YAML frontmatter must be an object")
    return value


def _validate_conflicts(entries: list[CatalogEntry]) -> None:
    _unique(((entry.runbook_id, entry.path) for entry in entries), "runbook_id")
    _unique(((Path(entry.path).name, entry.path) for entry in entries), "ACTIVE basename")

    identities: list[tuple[str, str]] = []
    topics: list[tuple[str, str]] = []
    signatures: list[tuple[str, str]] = []
    for entry in entries:
        identities.append((entry.runbook_id, entry.path))
        identities.extend((alias, entry.path) for alias in entry.aliases)
        topics.extend((row.topic, entry.path) for row in entry.authoritative_for)
        signatures.extend((row.signature, entry.path) for row in entry.error_signatures)
    _unique(identities, "runbook id/alias")
    _unique(topics, "topic")
    _unique(signatures, "error signature")


def _unique(values: Iterable[tuple[str, str]], label: str) -> None:
    seen: dict[str, str] = {}
    for value, path in values:
        if value in seen:
            raise CatalogError(f"duplicate {label} {value!r}: {seen[value]} and {path}")
        seen[value] = path


def _build_indexes(entries: list[CatalogEntry]) -> dict[str, dict[str, dict[str, str]]]:
    aliases: dict[str, dict[str, str]] = {}
    topics: dict[str, dict[str, str]] = {}
    signatures: dict[str, dict[str, str]] = {}
    for entry in entries:
        default_section = entry.authoritative_for[0].section
        for alias in entry.aliases:
            aliases[alias] = {"runbook_id": entry.runbook_id, "section": default_section}
        for row in entry.authoritative_for:
            topics[row.topic] = {"runbook_id": entry.runbook_id, "section": row.section}
        for row in entry.error_signatures:
            signatures[row.signature] = {"runbook_id": entry.runbook_id, "section": row.section}
    return {
        "aliases": dict(sorted(aliases.items())),
        "error_signatures": dict(sorted(signatures.items())),
        "topics": dict(sorted(topics.items())),
    }


def _render_router(catalog: dict[str, Any]) -> str:
    entries = {entry["runbook_id"]: entry for entry in catalog["entries"]}
    lines = [
        GENERATED_BANNER,
        "# Runbook Topic Router",
        "",
        "`CATALOG.json` is the sole machine authority. This file is a generated display surface.",
        "",
        "## Topics",
        "",
        "| Topic | Runbook | Section |",
        "|---|---|---|",
    ]
    lines.extend(_index_rows(catalog["indexes"]["topics"], entries))
    lines.extend(["", "## Error signatures", "", "| Signature | Runbook | Section |", "|---|---|---|"])
    lines.extend(_index_rows(catalog["indexes"]["error_signatures"], entries))
    lines.extend(["", "## Aliases", "", "| Alias | Runbook | Section |", "|---|---|---|"])
    lines.extend(_index_rows(catalog["indexes"]["aliases"], entries))
    return "\n".join(lines) + "\n"


def _index_rows(index: dict[str, dict[str, str]], entries: dict[str, dict[str, Any]]) -> list[str]:
    if not index:
        return ["| _None_ | — | — |"]
    rows: list[str] = []
    for key, target in index.items():
        entry = entries[target["runbook_id"]]
        link = _section_link(entry["path"], target["section"])
        rows.append(f"| `{_escape_cell(key)}` | `{entry['runbook_id']}` (`{entry['path']}`) | [{_escape_cell(target['section'])}]({link}) |")
    return rows


def _render_readme(readme: str, catalog: dict[str, Any], grandfathered_count: int) -> str:
    block_lines = [
        README_BEGIN,
        GENERATED_BANNER,
        "## Catalog inventory",
        "",
        f"ACTIVE catalog members: **{len(catalog['entries'])}**  ",
        f"Grandfathered source documents (readable by explicit Git path, absent from catalog authority): **{grandfathered_count}**",
        "",
        "| Runbook ID | Domain | Path | Authoritative topics and sections | Owner | Last verified |",
        "|---|---|---|---|---|---|",
    ]
    for entry in catalog["entries"]:
        authorities = "; ".join(
            f"`{row['topic']}` → [{_escape_cell(row['section'])}]({_section_link(entry['path'], row['section'])})"
            for row in entry["authoritative_for"]
        )
        block_lines.append(
            f"| `{entry['runbook_id']}` | `{entry['domain']}` | [`{entry['path']}`]({entry['path']}) | {authorities} | {_escape_cell(entry['owner'])} | {entry['last_verified_at']} |"
        )
    block_lines.append(README_END)
    block = "\n".join(block_lines)

    if README_BEGIN in readme or README_END in readme:
        if readme.count(README_BEGIN) != 1 or readme.count(README_END) != 1:
            raise CatalogError(f"{README_PATH}: generated inventory markers must occur exactly once")
        start = readme.index(README_BEGIN)
        end = readme.index(README_END, start) + len(README_END)
        rendered = readme[:start] + block + readme[end:]
    else:
        adoption = re.search(r"(?ms)^## Adoption status\n.*?(?=^## Status values\n)", readme)
        if adoption is None:
            raise CatalogError(f"{README_PATH}: missing generated markers or Adoption status section")
        rendered = readme[: adoption.start()] + block + "\n\n" + readme[adoption.end() :]
    return rendered.rstrip() + "\n"


def _section_link(path: str, section: str) -> str:
    anchor = section.casefold().replace("§", "")
    anchor = re.sub(r"[^\w\- ]", "", anchor)
    anchor = anchor.replace(" ", "-")
    return f"{path}#{anchor}"


def _escape_cell(value: str) -> str:
    return value.replace("|", "\\|")


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(handle, "wb") as temp:
            temp.write(content)
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)
