from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import UTC, date, datetime, time
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import quote

import yaml
from yaml.tokens import KeyToken, ScalarToken, ValueToken

from runbook_tools.catalog.model import (
    CatalogEntry,
    CatalogError,
    canonical_active_path,
)
from runbook_tools.catalog.sections import (
    declared_section_errors,
    legacy_heading_anchor,
)
from runbook_tools.frontmatter import CATALOG_METADATA_FIELDS
from runbook_tools.lint.conformance import structural_conformance_failures
from runbook_tools.strict_yaml import strict_yaml_load

SCHEMA_VERSION = 2
# A page may be untidy and still be indexed (Max directive S1491). It may not be
# indexed while asserting something false about itself. Only findings whose
# message matches one of these markers keep the power to refuse admission.
INTEGRITY_CONFORMANCE_MARKERS = ("cannot be in the future",)
LEGACY_AUTHORITY_BASE_SHA = "643e55d222fdebfb68063c0801ebd318fe4ae321"
LEGACY_PROJECTION_POLICY_PATH = "schemas/legacy_catalog_projection.policy.json"
LEGACY_PROJECTION_POLICY_SHA256 = (
    "5b43c6cfd5148417a39971f1b0821d08dadbd5b7cfef5f878a2dcf0eee4981ae"
)
LEGACY_PROJECTION_FIELDS = (
    "aliases",
    "authoritative_for",
    "error_signatures",
    "superseded_by",
    "supersedes",
)
CATALOG_PATH = "CATALOG.json"
ROUTER_PATH = "TOPIC-ROUTER.md"
README_PATH = "README.md"
GENERATED_BANNER = "<!-- Generated by runbook-catalog. DO NOT EDIT. -->"
README_BEGIN = "<!-- runbook-catalog:begin -->"
README_END = "<!-- runbook-catalog:end -->"
FRONTMATTER_RE = re.compile(
    r"\A---[ \t]*\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|$)",
    re.DOTALL,
)
FRONTMATTER_OPEN_RE = re.compile(r"\A---[ \t]*(?:\r?\n|$)")
RAW_MAPPING_KEY_RE = re.compile(
    # Accept both the ordinary ``key: value`` spelling and YAML's explicit
    # ``? key`` / ``: value`` mapping form. This projection is used only after
    # the real YAML scanner has already failed, so it must conservatively spot
    # catalog intent that occurs after the failure rather than parse values.
    r"(?m)^[ \t]*(?:\?[ \t]*)?(?:![^ \t\r\n]+[ \t]+|&[^ \t\r\n]+[ \t]+)*(?P<key>"
    r"[A-Za-z_][A-Za-z0-9_-]*"
    r'|"(?:\\.|[^"\r\n])*"'
    r"|'(?:''|[^'\r\n])*'"
    r")[ \t]*(?::|$)"
)
RAW_CATALOG_WORD_RE = re.compile(
    r"(?<![A-Za-z0-9_-])(?:"
    + "|".join(re.escape(field) for field in sorted(CATALOG_METADATA_FIELDS))
    + r")(?![A-Za-z0-9_-])"
)


@dataclass(frozen=True, slots=True)
class _ReviewedLegacyProjection:
    expected: dict[str, dict[str, Any]]
    allowed_paths: dict[str, frozenset[str]]

NON_OPERATIONAL_MARKDOWN_TREES = frozenset(
    {
        "archive",
        "audits",
        "contracts",
        "specs",
        "templates",
        "tests",
    }
)
IGNORED_TOP_LEVEL_TREES = frozenset(
    {
        ".agents",
        ".cache",
        ".codex",
        ".git",
        ".github",
        ".mypy_cache",
        ".nox",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".worktrees",
        *NON_OPERATIONAL_MARKDOWN_TREES,
    }
)
IGNORED_GENERATED_TREES = frozenset({"__pycache__", "node_modules"})


def _is_ignored_source_directory(relative: PurePosixPath) -> bool:
    if any(part in IGNORED_GENERATED_TREES for part in relative.parts):
        return True
    if len(relative.parts) != 1:
        return False
    top_level = relative.parts[0]
    return (
        top_level in IGNORED_TOP_LEVEL_TREES
        or top_level == ".venv"
        or top_level.startswith(".venv-")
    )


def is_source_relative_path(relative: str | PurePosixPath) -> bool:
    """Classify one normalized repository-relative Markdown candidate.

    Both working-tree discovery and immutable Git-tree materialization use this
    predicate so a newly admitted directory cannot disappear when the same
    catalog is validated by full SHA.
    """

    path = PurePosixPath(relative)
    if not is_admitted_source_tree_path(path):
        return False
    if path.suffix.lower() != ".md":
        return False
    return path.as_posix() not in {README_PATH, ROUTER_PATH}


def is_admitted_source_tree_path(relative: str | PurePosixPath) -> bool:
    """Return whether a Git-tree entry occupies the operational source zone.

    This broader predicate deliberately includes non-Markdown entries.  An
    immutable snapshot cannot determine whether a Git symlink or gitlink would
    become a directory when checked out, so validators use this classification
    to reject every non-regular entry in an admitted source tree rather than let
    one hide Markdown descendants.
    """

    path = PurePosixPath(relative)
    if path.is_absolute() or not path.parts or any(
        part in {"", ".", ".."} for part in path.parts
    ):
        return False
    if any(part in IGNORED_GENERATED_TREES for part in path.parts[:-1]):
        return False
    top_level = path.parts[0]
    if top_level in IGNORED_TOP_LEVEL_TREES:
        return False
    # ``.venv`` and ``.venv-*`` are directory conventions, not filename
    # prefixes. A root document such as ``.venv-recovery.MD`` remains an
    # operational candidate; descendants of an actual environment tree do not.
    return not (
        len(path.parts) > 1
        and (top_level == ".venv" or top_level.startswith(".venv-"))
    )


def source_paths(repo_root: Path) -> list[Path]:
    """Return the fail-closed operational Markdown candidate set.

    Unknown directories are included by default: moving a procedure from the
    repository root to a new ``docs/``-style tree must not let it evade corpus
    adjudication.  Only enumerated non-operational evidence, specification,
    test/template, and deployed-contract-format trees are excluded, along with
    enumerated top-level hidden/generated trees and dependency caches. Root
    generated README/router outputs are excluded by exact path. An unknown
    hidden tree or a nested directory that happens to be named ``archive`` is
    still admitted. This is the catalog membership set; only conformant ACTIVE
    metadata grants authority within it.
    """
    root = repo_root.resolve()
    selected: list[Path] = []
    def fail_walk(error: OSError) -> None:
        location = error.filename or str(root)
        raise CatalogError(
            f"source discovery cannot read {location}: {error.strerror or error}"
        ) from error

    for directory, child_directories, filenames in os.walk(
        root, followlinks=False, onerror=fail_walk
    ):
        current = Path(directory)
        relative_directory = current.relative_to(root)
        admitted_directories: list[str] = []
        for name in sorted(child_directories):
            relative_child = PurePosixPath(
                *(relative_directory.parts + (name,))
            )
            if _is_ignored_source_directory(relative_child):
                continue
            child = current / name
            if child.is_symlink():
                raise CatalogError(
                    f"{relative_child.as_posix()}: admitted source directory must not be a symlink"
                )
            admitted_directories.append(name)
        child_directories[:] = admitted_directories
        for filename in sorted(filenames):
            path = current / filename
            relative = path.relative_to(root)
            if not is_source_relative_path(relative.as_posix()):
                continue
            if path.is_symlink():
                raise CatalogError(
                    f"{relative.as_posix()}: admitted source document must not be a symlink"
                )
            selected.append(path)
    return sorted(selected, key=lambda path: path.relative_to(root).as_posix())


def build_catalog(
    repo_root: Path,
    *,
    current_utc_date: date | None = None,
    current_utc_datetime: datetime | None = None,
) -> tuple[dict[str, Any], int]:
    entries: list[CatalogEntry] = []
    grandfathered_count = 0
    root = repo_root.resolve()
    verification_clock, conformance_clock = _verification_clocks(
        current_utc_date,
        current_utc_datetime,
    )

    for path in source_paths(root):
        relative = path.relative_to(root).as_posix()
        frontmatter = _frontmatter(path)
        if frontmatter is None:
            grandfathered_count += 1
            continue
        if (
            frontmatter.get("status") in {"ACTIVE", "DRAFT"}
            and "runbook_id" not in frontmatter
        ):
            raise CatalogError(
                f"{relative}: {frontmatter['status']} document is missing required runbook_id"
            )
        if "runbook_id" not in frontmatter:
            grandfathered_count += 1
            continue
        if "status" not in frontmatter:
            raise CatalogError(f"{relative}: catalog opt-in is missing required status")
        if frontmatter.get("status") not in {"ACTIVE", "DRAFT"}:
            raise CatalogError(
                f"{relative}: catalog opt-in status must be ACTIVE or DRAFT"
            )
        if frontmatter["status"] != "ACTIVE":
            continue
        markdown = path.read_text()
        entry = CatalogEntry.from_frontmatter(
            frontmatter,
            relative,
            latest_verification_date=verification_clock,
        )
        # Conformance is a convention, not an admission condition.
        # Max directive S1491, and AC9 of the approved runbook truth-layer design
        # (specs/RUNBOOK-TRUTH-LAYER-S1487.md): a page's shape must never decide
        # whether it can be found. The deterministic A-K checks still run through
        # `runbook-lint`, where a failure is advice to the author.
        #
        # INTEGRITY_CONFORMANCE_MARKERS is the narrow exception. Those findings are
        # not untidiness, they are a page asserting something false about itself,
        # and indexing a lie is worse than indexing a mess. Everything else is
        # advice. Referential integrity of DECLARED metadata is enforced
        # separately below, because a catalog row pointing at a section that does
        # not exist makes the index lie rather than the page.
        integrity_failures = [
            finding
            for finding in structural_conformance_failures(
                markdown,
                root / "schemas",
                now=conformance_clock,
            )
            if any(
                marker in finding.message
                for marker in INTEGRITY_CONFORMANCE_MARKERS
            )
        ]
        if integrity_failures:
            details = "; ".join(
                f"{relative}:{finding.line or '?'}: catalog integrity check "
                f"{finding.check} failed: {finding.message}"
                for finding in integrity_failures
            )
            raise CatalogError(details)
        section_errors = declared_section_errors(
            markdown,
            relative,
            [
                (row.section, row.section_id)
                for row in (*entry.authoritative_for, *entry.error_signatures)
            ],
            authoritative_rows=[
                (row.section, row.section_id) for row in entry.authoritative_for
            ],
        )
        if section_errors:
            raise CatalogError("; ".join(dict.fromkeys(section_errors)))
        entries.append(entry)

    entries.sort(key=lambda entry: entry.runbook_id)
    _validate_conflicts(entries)
    projection = _reviewed_legacy_projection(root, revision="HEAD")
    if projection is not None:
        _enforce_reviewed_legacy_projection(
            [entry.as_dict() for entry in entries], projection
        )
    catalog = {
        "action_authority_eligible": False,
        "authority_admission": False,
        "entries": [entry.as_dict() for entry in entries],
        "indexes": _build_indexes(entries),
        "integrity_only": True,
        "schema_version": SCHEMA_VERSION,
        "semantic_verification": False,
        "status": "integrity_pass_unverified",
    }
    return catalog, grandfathered_count


def _reviewed_legacy_projection(
    repo_root: Path,
    *,
    revision: str,
) -> _ReviewedLegacyProjection | None:
    """Load the immutable baseline plus digest-pinned reviewed projection.

    Non-Git directories are render-only fixtures and cannot produce immutable
    authority. Every actual Git repository must contain the exact rollout
    object, and the generation/pinned-validation revision must descend from it.
    Tests that need unrelated synthetic Git history must monkeypatch this loader
    explicitly; remote names, working manifests, and working catalogs are never
    test or trust signals.
    """

    root = repo_root.resolve()
    try:
        top_level = subprocess.run(
            [
                "git",
                "--no-replace-objects",
                "-C",
                str(root),
                "rev-parse",
                "--show-toplevel",
            ],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None
    if Path(top_level).resolve() != root:
        raise CatalogError(f"repo_root must be the Git worktree root ({top_level})")

    baseline = _resolve_exact_git_commit(
        root,
        LEGACY_AUTHORITY_BASE_SHA,
        "immutable legacy authority baseline",
    )
    target = _resolve_exact_git_commit(root, revision, "catalog revision")
    ancestry = subprocess.run(
        [
            "git",
            "--no-replace-objects",
            "-C",
            str(root),
            "merge-base",
            "--is-ancestor",
            baseline,
            target,
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    if ancestry.returncode == 1:
        raise CatalogError(
            f"catalog revision {target} is not a descendant of immutable rollout "
            f"baseline {baseline}"
        )
    if ancestry.returncode != 0:
        raise CatalogError(
            "cannot verify catalog baseline ancestry: "
            + (ancestry.stderr.strip() or "git merge-base failed")
        )

    try:
        raw_catalog = subprocess.run(
            [
                "git",
                "--no-replace-objects",
                "-C",
                str(root),
                "show",
                f"{LEGACY_AUTHORITY_BASE_SHA}:{CATALOG_PATH}",
            ],
            check=True,
            capture_output=True,
        ).stdout
        catalog = _strict_json_object(raw_catalog, "immutable legacy authority catalog")
    except (subprocess.CalledProcessError, UnicodeError, json.JSONDecodeError) as exc:
        raise CatalogError(
            "cannot read immutable legacy authority catalog at "
            f"{LEGACY_AUTHORITY_BASE_SHA}: {exc}"
        ) from exc
    if type(catalog.get("entries")) is not list:
        raise CatalogError("immutable legacy authority catalog has invalid structure")
    baseline_entries: dict[str, dict[str, Any]] = {}
    baseline_paths: dict[str, str] = {}
    for index, entry in enumerate(catalog["entries"]):
        if type(entry) is not dict or type(entry.get("runbook_id")) is not str:
            raise CatalogError(
                f"immutable legacy authority catalog entry {index} has no runbook_id"
            )
        runbook_id = entry["runbook_id"]
        if runbook_id in baseline_entries:
            raise CatalogError(
                "immutable legacy authority catalog IDs must be non-empty and unique"
            )
        if type(entry.get("path")) is not str:
            raise CatalogError(
                f"immutable legacy authority catalog entry {index} has no path"
            )
        baseline_entries[runbook_id] = {
            field: entry.get(field) for field in LEGACY_PROJECTION_FIELDS
        }
        baseline_paths[runbook_id] = entry["path"]
    if not baseline_entries:
        raise CatalogError(
            "immutable legacy authority catalog IDs must be non-empty and unique"
        )
    policy = _load_projection_policy(root / LEGACY_PROJECTION_POLICY_PATH)
    if policy.get("rollout_base_sha") != baseline:
        raise CatalogError("legacy projection policy rollout_base_sha is not exact")
    expected_population = policy.get("expected_population")
    if type(expected_population) is not int or expected_population != len(
        baseline_entries
    ):
        raise CatalogError(
            "legacy projection policy expected_population does not match baseline"
        )
    moves = policy.get("canonical_path_moves")
    overrides = policy.get("entry_overrides")
    if type(moves) is not list or not all(type(item) is str for item in moves):
        raise CatalogError("legacy projection policy canonical_path_moves is invalid")
    if len(moves) != len(set(moves)) or not set(moves) <= baseline_entries.keys():
        raise CatalogError("legacy projection policy canonical_path_moves is not exact")
    if type(overrides) is not dict or not set(overrides) <= baseline_entries.keys():
        raise CatalogError("legacy projection policy entry_overrides is invalid")
    for runbook_id, raw_override in overrides.items():
        if type(raw_override) is not dict or set(raw_override) != set(
            LEGACY_PROJECTION_FIELDS
        ):
            raise CatalogError(
                f"legacy projection override {runbook_id!r} must define exactly "
                + ", ".join(LEGACY_PROJECTION_FIELDS)
            )
        baseline_entries[runbook_id] = {
            field: raw_override[field] for field in LEGACY_PROJECTION_FIELDS
        }
    allowed_paths = {
        runbook_id: frozenset(
            {
                baseline_path,
                *(
                    [canonical_active_path(runbook_id)]
                    if runbook_id in set(moves)
                    else []
                ),
            }
        )
        for runbook_id, baseline_path in baseline_paths.items()
    }
    return _ReviewedLegacyProjection(
        expected=baseline_entries,
        allowed_paths=allowed_paths,
    )


def _resolve_exact_git_commit(root: Path, revision: str, label: str) -> str:
    try:
        resolved = subprocess.run(
            [
                "git",
                "--no-replace-objects",
                "-C",
                str(root),
                "rev-parse",
                "--verify",
                f"{revision}^{{commit}}",
            ],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except subprocess.CalledProcessError as exc:
        raise CatalogError(
            f"{label} is unavailable: {exc.stderr.strip()}"
        ) from exc
    if re.fullmatch(r"[0-9a-f]{40}", revision) is not None and resolved != revision:
        raise CatalogError(f"{label} resolves to {resolved}, expected exact {revision}")
    return resolved


def _load_projection_policy(path: Path) -> dict[str, Any]:
    if path.is_symlink() or not path.is_file():
        raise CatalogError(f"legacy projection policy must be a regular file: {path}")
    try:
        payload = path.read_bytes()
        policy = _strict_json_object(payload, str(path))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise CatalogError(f"legacy projection policy is invalid: {exc}") from exc
    digest = hashlib.sha256(payload).hexdigest()
    if digest != LEGACY_PROJECTION_POLICY_SHA256:
        raise CatalogError(
            "legacy projection policy digest mismatch: trusted package projection "
            f"requires {LEGACY_PROJECTION_POLICY_SHA256}, found {digest}"
        )
    expected_keys = {
        "$schema",
        "canonical_path_moves",
        "contract_version",
        "entry_overrides",
        "expected_population",
        "rollout_base_sha",
    }
    if set(policy) != expected_keys:
        raise CatalogError("legacy projection policy fields are not exact")
    if policy.get("contract_version") != "ai.market/legacy-catalog-projection/v1":
        raise CatalogError("legacy projection policy contract_version is invalid")
    return policy


def _strict_json_object(payload: bytes, label: str) -> dict[str, Any]:
    def reject_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise json.JSONDecodeError(f"duplicate key {key!r}", key, 0)
            result[key] = value
        return result

    value = json.loads(payload, object_pairs_hook=reject_duplicates)
    if type(value) is not dict:
        raise json.JSONDecodeError(f"{label} must be a JSON object", "", 0)
    return value


def _enforce_reviewed_legacy_projection(
    entries: list[dict[str, Any]],
    projection: _ReviewedLegacyProjection,
) -> None:
    actual: dict[str, dict[str, Any]] = {}
    for entry in entries:
        runbook_id = entry.get("runbook_id")
        if type(runbook_id) is not str:
            raise CatalogError("catalog projection contains an invalid runbook_id")
        if runbook_id in actual:
            raise CatalogError(
                f"catalog projection contains duplicate runbook_id {runbook_id!r}"
            )
        actual[runbook_id] = entry
    expected_ids = set(projection.expected)
    actual_ids = set(actual)
    missing = sorted(expected_ids - actual_ids)
    unexpected = sorted(actual_ids - expected_ids)
    if missing or unexpected:
        details: list[str] = []
        if missing:
            details.append("missing=" + ", ".join(missing))
        if unexpected:
            details.append("unexpected=" + ", ".join(unexpected))
        raise CatalogError(
            "catalog integrity-only legacy population differs from reviewed rollout "
            "projection: "
            + "; ".join(details)
        )
    errors: list[str] = []
    for runbook_id in sorted(expected_ids):
        entry = actual[runbook_id]
        path = entry.get("path")
        if path not in projection.allowed_paths[runbook_id]:
            errors.append(
                f"{runbook_id}.path {path!r} is not an explicitly reviewed legacy path"
            )
        for field in LEGACY_PROJECTION_FIELDS:
            if entry.get(field) != projection.expected[runbook_id][field]:
                errors.append(
                    f"{runbook_id}.{field} differs from reviewed legacy projection"
                )
    if errors:
        raise CatalogError(
            "catalog integrity-only discovery projection drift: " + "; ".join(errors)
        )


def render_outputs(
    repo_root: Path,
    *,
    current_utc_date: date | None = None,
    current_utc_datetime: datetime | None = None,
) -> dict[str, bytes]:
    catalog, grandfathered_count = build_catalog(
        repo_root,
        current_utc_date=current_utc_date,
        current_utc_datetime=current_utc_datetime,
    )
    catalog_bytes = (json.dumps(catalog, indent=2, sort_keys=True) + "\n").encode()
    router_bytes = _render_router(catalog).encode()
    readme_path = repo_root / README_PATH
    if not readme_path.is_file():
        raise CatalogError(f"{README_PATH}: file is required for generated inventory")
    readme_bytes = _render_readme(readme_path.read_text(), catalog, grandfathered_count).encode()
    return {
        CATALOG_PATH: catalog_bytes,
        ROUTER_PATH: router_bytes,
        README_PATH: readme_bytes,
    }


def generate_catalog(
    repo_root: Path,
    *,
    current_utc_date: date | None = None,
    current_utc_datetime: datetime | None = None,
) -> dict[str, bytes]:
    outputs = render_outputs(
        repo_root,
        current_utc_date=current_utc_date,
        current_utc_datetime=current_utc_datetime,
    )
    for relative, content in outputs.items():
        _atomic_write(repo_root / relative, content)
    return outputs


def check_catalog(
    repo_root: Path,
    *,
    current_utc_date: date | None = None,
    current_utc_datetime: datetime | None = None,
) -> list[str]:
    outputs = render_outputs(
        repo_root,
        current_utc_date=current_utc_date,
        current_utc_datetime=current_utc_datetime,
    )
    drifted: list[str] = []
    for relative, expected in outputs.items():
        path = repo_root / relative
        if not path.is_file() or path.read_bytes() != expected:
            drifted.append(relative)
    return drifted


def _verification_clocks(
    current_utc_date: date | None,
    current_utc_datetime: datetime | None,
) -> tuple[date, datetime]:
    if current_utc_datetime is not None:
        instant = (
            current_utc_datetime.replace(tzinfo=UTC)
            if current_utc_datetime.tzinfo is None
            else current_utc_datetime.astimezone(UTC)
        )
        if current_utc_date is not None and current_utc_date != instant.date():
            raise CatalogError(
                "current_utc_date must match current_utc_datetime in UTC"
            )
        return current_utc_date or instant.date(), instant
    if current_utc_date is not None:
        return current_utc_date, datetime.combine(
            current_utc_date,
            time.max,
            tzinfo=UTC,
        )
    instant = datetime.now(UTC)
    return instant.date(), instant


def _frontmatter(path: Path) -> dict[str, Any] | None:
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if match is None:
        opener = FRONTMATTER_OPEN_RE.match(text)
        if opener is not None and _has_catalog_field_hint(text[opener.end() :]):
            raise CatalogError(
                f"{path}: catalog frontmatter is missing its closing delimiter"
            )
        return None
    raw_frontmatter = match.group(1)
    # Parse before classification so YAML-equivalent spellings such as quoted
    # ACTIVE cannot evade strict catalog admission. The raw hint is used only to
    # make malformed opt-in YAML fail while preserving thematic-break Markdown.
    has_catalog_hint = _has_catalog_field_hint(raw_frontmatter)
    try:
        value = strict_yaml_load(raw_frontmatter)
    except yaml.YAMLError as exc:
        if has_catalog_hint:
            raise CatalogError(f"{path}: invalid YAML frontmatter: {exc}") from exc
        return None
    if not isinstance(value, dict):
        if has_catalog_hint:
            raise CatalogError(f"{path}: YAML frontmatter must be an object")
        return None
    if "runbook_id" not in value and value.get("status") not in {"ACTIVE", "DRAFT"}:
        return None
    return value


def _has_catalog_field_hint(raw_frontmatter: str) -> bool:
    """Recognize catalog mapping keys even when their YAML spelling is quoted.

    Scanning, unlike a raw regex, resolves quoted scalar escapes and still lets
    us observe a catalog key before a later syntax or duplicate-key failure.
    Non-catalog thematic-break pseudo-frontmatter remains grandfathered.
    """

    pending_key = False
    key_value: object = None
    try:
        for token in yaml.scan(raw_frontmatter):
            if isinstance(token, KeyToken):
                pending_key = True
                key_value = None
                continue
            if pending_key and isinstance(token, ScalarToken):
                key_value = token.value
                continue
            if pending_key and isinstance(token, ValueToken):
                if key_value in CATALOG_METADATA_FIELDS:
                    return True
                pending_key = False
                key_value = None
    except yaml.YAMLError:
        # A key already observed before the scanner reached malformed syntax is
        # enough to classify the frontmatter as an attempted catalog opt-in. A
        # conservative line projection also catches a catalog key that appears
        # only after an earlier scanner error; it accepts only mapping-key
        # spellings at line start, not catalog words embedded in prose.
        return (
            key_value in CATALOG_METADATA_FIELDS
            or _raw_catalog_field_hint(raw_frontmatter)
        )
    return False


def _raw_catalog_field_hint(raw_frontmatter: str) -> bool:
    for match in RAW_MAPPING_KEY_RE.finditer(raw_frontmatter):
        spelling = match.group("key")
        if spelling[:1] in {'"', "'"}:
            try:
                key = yaml.safe_load(spelling)
            except yaml.YAMLError:
                continue
        else:
            key = spelling
        if key in CATALOG_METADATA_FIELDS:
            return True
    # YAML also permits complex keys (for example a block-scalar key). Once the
    # scanner has failed, fully recovering that grammar would recreate a second
    # parser and another bypass surface. A whole-word catalog field anywhere in
    # the malformed delimiter block is therefore treated conservatively as
    # catalog intent. Ambiguous malformed metadata must be repaired, not hidden
    # as grandfathered prose.
    return RAW_CATALOG_WORD_RE.search(raw_frontmatter) is not None


def _validate_conflicts(entries: list[CatalogEntry]) -> None:
    _unique(((entry.runbook_id, entry.path) for entry in entries), "runbook_id")
    _unique(((Path(entry.path).name, entry.path) for entry in entries), "ACTIVE basename")

    identities: list[tuple[str, str]] = []
    topics: list[tuple[str, str]] = []
    signatures: list[tuple[str, str]] = []
    for entry in entries:
        identities.append((entry.runbook_id, entry.path))
        identities.extend((alias, entry.path) for alias in entry.aliases)
        topics.extend((row.topic, entry.path) for row in entry.authoritative_for)
        signatures.extend((row.signature, entry.path) for row in entry.error_signatures)
    _unique(identities, "runbook id/alias")
    _unique(topics, "topic")
    _unique(signatures, "error signature")

    resolver_keys: list[
        tuple[str, str, str, tuple[str, str, str | None]]
    ] = []
    for entry in entries:
        default = entry.authoritative_for[0]
        default_target = (
            entry.runbook_id,
            default.section,
            default.section_id,
        )
        resolver_keys.append(
            (entry.runbook_id, "runbook_id", entry.path, default_target)
        )
        resolver_keys.extend(
            (alias, "alias", entry.path, default_target)
            for alias in entry.aliases
        )
        resolver_keys.extend(
            (
                row.topic,
                "topic",
                entry.path,
                (entry.runbook_id, row.section, row.section_id),
            )
            for row in entry.authoritative_for
        )
        resolver_keys.extend(
            (
                row.signature,
                "error_signature",
                entry.path,
                (entry.runbook_id, row.section, row.section_id),
            )
            for row in entry.error_signatures
        )
    _unique_resolver_namespace(resolver_keys)


def _unique(values: Iterable[tuple[str, str]], label: str) -> None:
    seen: dict[str, str] = {}
    for value, path in values:
        if value in seen:
            raise CatalogError(f"duplicate {label} {value!r}: {seen[value]} and {path}")
        seen[value] = path


def _unique_resolver_namespace(
    values: Iterable[
        tuple[str, str, str, tuple[str, str, str | None]]
    ],
) -> None:
    seen: dict[str, tuple[str, str, tuple[str, str, str | None]]] = {}
    for value, namespace, path, target in values:
        previous = seen.get(value)
        if previous is not None:
            previous_namespace, previous_path, previous_target = previous
            if previous_namespace != namespace and previous_target != target:
                raise CatalogError(
                    f"ambiguous resolver key {value!r}: "
                    f"{previous_namespace} in {previous_path} conflicts with "
                    f"{namespace} in {path}"
                )
        else:
            seen[value] = (namespace, path, target)


def _build_indexes(entries: list[CatalogEntry]) -> dict[str, dict[str, dict[str, str]]]:
    aliases: dict[str, dict[str, str]] = {}
    topics: dict[str, dict[str, str]] = {}
    signatures: dict[str, dict[str, str]] = {}
    for entry in entries:
        default_authority = entry.authoritative_for[0]
        for alias in entry.aliases:
            aliases[alias] = _index_target(
                entry.runbook_id,
                default_authority.section,
                default_authority.section_id,
            )
        for row in entry.authoritative_for:
            topics[row.topic] = _index_target(
                entry.runbook_id,
                row.section,
                row.section_id,
            )
        for row in entry.error_signatures:
            signatures[row.signature] = _index_target(
                entry.runbook_id,
                row.section,
                row.section_id,
            )
    return {
        "aliases": dict(sorted(aliases.items())),
        "error_signatures": dict(sorted(signatures.items())),
        "topics": dict(sorted(topics.items())),
    }


def _index_target(
    runbook_id: str,
    section: str,
    section_id: str | None,
) -> dict[str, str]:
    target = {"runbook_id": runbook_id, "section": section}
    if section_id is not None:
        target["section_id"] = section_id
    return target


def _render_router(catalog: dict[str, Any]) -> str:
    entries = {entry["runbook_id"]: entry for entry in catalog["entries"]}
    lines = [
        GENERATED_BANNER,
        "# Runbook Topic Router",
        "",
        "`CATALOG.json` is the sole machine authority. This file is a generated display surface.",
        "The router intentionally lists only ACTIVE authority keys. Agents must first use the immutable all-corpus search; pending and archived documents are discoverable there with warnings but never appear here as authority.",
        "",
        "## Topics",
        "",
        "| Topic | Runbook | Section |",
        "|---|---|---|",
    ]
    lines.extend(_index_rows(catalog["indexes"]["topics"], entries))
    lines.extend(["", "## Error signatures", "", "| Signature | Runbook | Section |", "|---|---|---|"])
    lines.extend(_index_rows(catalog["indexes"]["error_signatures"], entries))
    lines.extend(["", "## Aliases", "", "| Alias | Runbook | Section |", "|---|---|---|"])
    lines.extend(_index_rows(catalog["indexes"]["aliases"], entries))
    return "\n".join(lines) + "\n"


def _index_rows(index: dict[str, dict[str, str]], entries: dict[str, dict[str, Any]]) -> list[str]:
    if not index:
        return ["| _None_ | — | — |"]
    rows: list[str] = []
    for key, target in index.items():
        entry = entries[target["runbook_id"]]
        link = _section_link(entry["path"], target["section"], target.get("section_id"))
        rows.append(
            f"| `{_escape_code_cell(key)}` | `{entry['runbook_id']}` "
            f"(`{entry['path']}`) | "
            f"[{_escape_markdown_text(target['section'])}]({link}) |"
        )
    return rows


def _render_readme(readme: str, catalog: dict[str, Any], grandfathered_count: int) -> str:
    block_lines = [
        README_BEGIN,
        GENERATED_BANNER,
        "## Catalog inventory",
        "",
        f"ACTIVE catalog members: **{len(catalog['entries'])}**  ",
        f"Grandfathered source documents (globally searchable as warned discovery, absent from catalog authority): **{grandfathered_count}**",
        "",
        "| Runbook ID | Domain | Path | Authoritative topics and sections | Owner | Last verified |",
        "|---|---|---|---|---|---|",
    ]
    for entry in catalog["entries"]:
        authorities = "; ".join(
            f"`{row['topic']}` → "
            f"[{_escape_markdown_text(row['section'])}]"
            f"({_section_link(entry['path'], row['section'], row.get('section_id'))})"
            for row in entry["authoritative_for"]
        )
        block_lines.append(
            f"| `{entry['runbook_id']}` | `{entry['domain']}` | "
            f"[`{entry['path']}`]({_encoded_path(entry['path'])}) | "
            f"{authorities} | {_escape_markdown_text(entry['owner'])} | "
            f"{entry['last_verified_at']} |"
        )
    block_lines.append(README_END)
    block = "\n".join(block_lines)

    if README_BEGIN in readme or README_END in readme:
        if readme.count(README_BEGIN) != 1 or readme.count(README_END) != 1:
            raise CatalogError(f"{README_PATH}: generated inventory markers must occur exactly once")
        start = readme.index(README_BEGIN)
        end = readme.index(README_END, start) + len(README_END)
        rendered = readme[:start] + block + readme[end:]
    else:
        adoption = re.search(r"(?ms)^## Adoption status\n.*?(?=^## Status values\n)", readme)
        if adoption is None:
            raise CatalogError(f"{README_PATH}: missing generated markers or Adoption status section")
        rendered = readme[: adoption.start()] + block + "\n\n" + readme[adoption.end() :]
    return rendered.rstrip() + "\n"


def _section_link(path: str, section: str, section_id: str | None = None) -> str:
    encoded_path = _encoded_path(path)
    if section_id is not None:
        return f"{encoded_path}#rb-section-{quote(section_id, safe='-._~')}"
    anchor = legacy_heading_anchor(section)
    if not anchor:
        raise CatalogError(
            f"section {section!r} cannot produce a safe legacy Markdown anchor; "
            "declare section_id"
        )
    return f"{encoded_path}#{quote(anchor, safe='-._~')}"


def _encoded_path(path: str) -> str:
    return quote(path, safe="/-._~")


def _escape_code_cell(value: str) -> str:
    return value.replace("\\", "\\\\").replace("|", "\\|")


def _escape_markdown_text(value: str) -> str:
    return re.sub(r"([\\`*_{}\[\]()<>#+.!|])", r"\\\1", value)


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(handle, "wb") as temp:
            temp.write(content)
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)
